FROM node:boron
# make and copy 
RUN mkdir -p /code
COPY package.json /code
COPY . /code
# only copy directory if you are not using volume mounts
# COPY . /code
# set working directory to /code
WORKDIR /code
RUN npm install
EXPOSE 3000
CMD npm run start